services:
  - type: web
    name: code-image-generator
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
